version: "3"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    volumes:
      - ./database/volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASS}
      - APP_DB_NAME=${APP_DB_NAME}

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
